databases:
  - name: jayna-db
    databaseName: jayna
    user: jayna
    plan: free

services:
  - type: web
    name: jayna-backend
    plan: starter
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /management/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - key: DB_HOST
        fromDatabase:
          name: jayna-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: jayna-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: jayna-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: jayna-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: jayna-db
          property: password
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET
        generateValue: true
      - key: STORAGE_LOCAL_PATH
        value: /tmp/jayna/documents

staticSites:
  - name: jayna-frontend
    plan: free
    buildCommand: "npm install && npm run webapp:prod"
    staticPublishPath: target/classes/static
    envVars:
      - key: SERVER_API_URL
        fromService:
          name: jayna-backend
          type: web
          property: host
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
