export const Authority = {
  ADMIN: "ROLE_ADMIN",
  USER: "ROLE_USER",
  USER_LIGHT: "ROLE_USER_LIGHT",
  USER_BASIC: "ROLE_USER_BASIC",
  USER_PRO: "ROLE_USER_PRO",
  BUSINESS_LIGHT: "ROLE_USER_LIGHT",
  BUSINESS_BASIC: "ROLE_BUSINESS_BASIC",
  BUSINESS_PRO: "ROLE_BUSINESS_PRO",
};
